# DataPalette Configuration File

# Input and Output
input: /path/to/input
output_dir: /path/to/output
input-type: images  # choices: video, images, single_image
pipeline: custom  # choices: gan, unet, diffusion, custom, showcase

# Video-specific options
fps: 1  # Frames per second to extract (for video input)

# GAN pipeline specific options
crop-size: [256, 256]  # Crop size for GAN pipeline
num-crops: 5  # Number of crops per frame (for GAN pipeline)

# Tiling options
tile: false  # Apply tiling to input images
tile-size: [256, 256]  # Size of tiles (width height)
tile-overlap: 0.0  # Overlap between tiles (0.0 to 1.0)

# Custom pipeline options
rotate: true  # Apply rotation
rotate-angles: [90, 180, 270]  # Rotation angles
mirror: true  # Apply mirroring
brightness-contrast: true  # Adjust brightness and contrast
brightness-range: [0.5, 1.5]  # Brightness adjustment range
contrast-range: [0.5, 1.5]  # Contrast adjustment range
noise: false  # Add noise
noise-type: gaussian  # Type of noise to add (choices: gaussian, salt_and_pepper)
noise-amount: 0.05  # Amount of noise to add
crop: false  # Apply random cropping
pca: true  # Apply PCA color augmentation
pca-alpha-std: 0.1  # Standard deviation for PCA color augmentation
hsv: true  # Convert to HSV and combine
lab: false  # Convert to LAB and combine
fourier: false  # Apply Fourier transform
gradient: true  # Add gradient channels
multispectral: false  # Convert to multispectral
edge: true  # Add edge channels
green: false  # Enhance green channel
custom-filter: null  # Apply custom filter (choices: emboss, sharpen)